### ISSUE TITLE
Fix PDCurses support for Windows

### ISSUE THREAD

**Issue by swashdev** [swashdev/SwashRL#2]
[PDCurses] support has been dropped for a while, and the reason for this is that the Windows version of dub can't seem to interface with any compiled version of the PDCurses library for Windows, even with a working [PDCurses wrapper].

The issue has apparently been fixed for Linux, but Windows support remains broken.

## Update 2018-08-29

Following a comment by unleashy [Issue] on the [PDCurses wrapper] GitHub page, the compile now works, but the compiled program crashes on Windows without so much as an error message.  The cause of the error remains a mystery, but at least it compiles now.

[PDCurses]: https://github.com/wmcbrine/PDCurses
[PDCurses wrapper]: https://github.com/unleashy/pdcurses-d
[Issue]: https://github.com/unleashy/pdcurses-d/issues/1#issuecomment-416691976

**Comment by unleashy** [comment]
Hi! Compiling and running works fine with pdcurses for me. You may be using a .lib that is x86 when you really want a x64 one, or something like that—although it would probably error out in the linking step, and not at runtime :)

Try checking like, the return value by doing `echo %ERRORLEVEL%` after the program crashes, then looking it up to see what it's about.

**Comment by swashdev** [comment]
Thank you very much for your advice, unleashy.  Echoing the error level gave me some absurd negative integer value which didn't help much, lol.  However, I did try compiling a newer version of PDCurses from source using nmake and that version of the library has been much more cooperative.

The game is in an essentially playable state on PDCurses now, so I'm going to close this issue.  Thank you very much again for your help.

**Comment by unleashy** [comment]
no problem :)

**Comment by swashdev** [comment]
Leaving this comment for the record, the problem might have been simpler than either unleashy or I figured out.  It turns out that the compiled PDCurses library for Windows that I had works with LDC but not with DmD, which means that when I initially tried to work with PDCurses it was failing because I wasn't using LDC at the time.

I'm not sure what the cause of this error is, but my best guess is that DmD doesn't play nice with the linker that I was using for the PDCurses compile.  Perhaps a MinGW compile of PDCurses would have got the job done better.
